model.conv_in: 51.2
model.conv_out: 4096.0
model.down_blocks.0.attentions.0.proj_in: 4096.0
model.down_blocks.0.attentions.0.proj_out: 4096.0
model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_k: 4096.0
model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_out.0: 4096.0
model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_q: 4096.0
model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_v: 4096.0
model.down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_k: 184.8
model.down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_out.0: 4096.0
model.down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_q: 4096.0
model.down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_v: 184.8
model.down_blocks.0.attentions.0.transformer_blocks.0.ff.net.0.proj: 4096.0
model.down_blocks.0.attentions.0.transformer_blocks.0.ff.net.2: 16384.0
model.down_blocks.0.attentions.1.proj_in: 4096.0
model.down_blocks.0.attentions.1.proj_out: 4096.0
model.down_blocks.0.attentions.1.transformer_blocks.0.attn1.to_k: 4096.0
model.down_blocks.0.attentions.1.transformer_blocks.0.attn1.to_out.0: 4096.0
model.down_blocks.0.attentions.1.transformer_blocks.0.attn1.to_q: 4096.0
model.down_blocks.0.attentions.1.transformer_blocks.0.attn1.to_v: 4096.0
model.down_blocks.0.attentions.1.transformer_blocks.0.attn2.to_k: 184.8
model.down_blocks.0.attentions.1.transformer_blocks.0.attn2.to_out.0: 4096.0
model.down_blocks.0.attentions.1.transformer_blocks.0.attn2.to_q: 4096.0
model.down_blocks.0.attentions.1.transformer_blocks.0.attn2.to_v: 184.8
model.down_blocks.0.attentions.1.transformer_blocks.0.ff.net.0.proj: 4096.0
model.down_blocks.0.attentions.1.transformer_blocks.0.ff.net.2: 16384.0
model.down_blocks.0.downsamplers.0.conv: 4096.0
model.down_blocks.0.resnets.0.conv1: 4096.0
model.down_blocks.0.resnets.0.conv2: 4096.0
model.down_blocks.0.resnets.0.time_emb_proj: 4.0
model.down_blocks.0.resnets.1.conv1: 4096.0
model.down_blocks.0.resnets.1.conv2: 4096.0
model.down_blocks.0.resnets.1.time_emb_proj: 4.0
model.down_blocks.1.attentions.0.proj_in: 2048.0
model.down_blocks.1.attentions.0.proj_out: 2048.0
model.down_blocks.1.attentions.0.transformer_blocks.0.attn1.to_k: 2048.0
model.down_blocks.1.attentions.0.transformer_blocks.0.attn1.to_out.0: 2048.0
model.down_blocks.1.attentions.0.transformer_blocks.0.attn1.to_q: 2048.0
model.down_blocks.1.attentions.0.transformer_blocks.0.attn1.to_v: 2048.0
model.down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_k: 184.8
model.down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_out.0: 2048.0
model.down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_q: 2048.0
model.down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_v: 184.8
model.down_blocks.1.attentions.0.transformer_blocks.0.ff.net.0.proj: 2048.0
model.down_blocks.1.attentions.0.transformer_blocks.0.ff.net.2: 8192.0
model.down_blocks.1.attentions.1.proj_in: 2048.0
model.down_blocks.1.attentions.1.proj_out: 2048.0
model.down_blocks.1.attentions.1.transformer_blocks.0.attn1.to_k: 2048.0
model.down_blocks.1.attentions.1.transformer_blocks.0.attn1.to_out.0: 2048.0
model.down_blocks.1.attentions.1.transformer_blocks.0.attn1.to_q: 2048.0
model.down_blocks.1.attentions.1.transformer_blocks.0.attn1.to_v: 2048.0
model.down_blocks.1.attentions.1.transformer_blocks.0.attn2.to_k: 184.8
model.down_blocks.1.attentions.1.transformer_blocks.0.attn2.to_out.0: 2048.0
model.down_blocks.1.attentions.1.transformer_blocks.0.attn2.to_q: 2048.0
model.down_blocks.1.attentions.1.transformer_blocks.0.attn2.to_v: 184.8
model.down_blocks.1.attentions.1.transformer_blocks.0.ff.net.0.proj: 2048.0
model.down_blocks.1.attentions.1.transformer_blocks.0.ff.net.2: 8192.0
model.down_blocks.1.downsamplers.0.conv: 2048.0
model.down_blocks.1.resnets.0.conv1: 1024.0
model.down_blocks.1.resnets.0.conv2: 2048.0
model.down_blocks.1.resnets.0.conv_shortcut: 1024.0
model.down_blocks.1.resnets.0.time_emb_proj: 4.0
model.down_blocks.1.resnets.1.conv1: 2048.0
model.down_blocks.1.resnets.1.conv2: 2048.0
model.down_blocks.1.resnets.1.time_emb_proj: 4.0
model.down_blocks.2.attentions.0.proj_in: 1024.0
model.down_blocks.2.attentions.0.proj_out: 1024.0
model.down_blocks.2.attentions.0.transformer_blocks.0.attn1.to_k: 1024.0
model.down_blocks.2.attentions.0.transformer_blocks.0.attn1.to_out.0: 1024.0
model.down_blocks.2.attentions.0.transformer_blocks.0.attn1.to_q: 1024.0
model.down_blocks.2.attentions.0.transformer_blocks.0.attn1.to_v: 1024.0
model.down_blocks.2.attentions.0.transformer_blocks.0.attn2.to_k: 184.8
model.down_blocks.2.attentions.0.transformer_blocks.0.attn2.to_out.0: 1024.0
model.down_blocks.2.attentions.0.transformer_blocks.0.attn2.to_q: 1024.0
model.down_blocks.2.attentions.0.transformer_blocks.0.attn2.to_v: 184.8
model.down_blocks.2.attentions.0.transformer_blocks.0.ff.net.0.proj: 1024.0
model.down_blocks.2.attentions.0.transformer_blocks.0.ff.net.2: 4096.0
model.down_blocks.2.attentions.1.proj_in: 1024.0
model.down_blocks.2.attentions.1.proj_out: 1024.0
model.down_blocks.2.attentions.1.transformer_blocks.0.attn1.to_k: 1024.0
model.down_blocks.2.attentions.1.transformer_blocks.0.attn1.to_out.0: 1024.0
model.down_blocks.2.attentions.1.transformer_blocks.0.attn1.to_q: 1024.0
model.down_blocks.2.attentions.1.transformer_blocks.0.attn1.to_v: 1024.0
model.down_blocks.2.attentions.1.transformer_blocks.0.attn2.to_k: 184.8
model.down_blocks.2.attentions.1.transformer_blocks.0.attn2.to_out.0: 1024.0
model.down_blocks.2.attentions.1.transformer_blocks.0.attn2.to_q: 1024.0
model.down_blocks.2.attentions.1.transformer_blocks.0.attn2.to_v: 184.8
model.down_blocks.2.attentions.1.transformer_blocks.0.ff.net.0.proj: 1024.0
model.down_blocks.2.attentions.1.transformer_blocks.0.ff.net.2: 4096.0
model.down_blocks.2.downsamplers.0.conv: 1024.0
model.down_blocks.2.resnets.0.conv1: 512.0
model.down_blocks.2.resnets.0.conv2: 1024.0
model.down_blocks.2.resnets.0.conv_shortcut: 512.0
model.down_blocks.2.resnets.0.time_emb_proj: 4.0
model.down_blocks.2.resnets.1.conv1: 1024.0
model.down_blocks.2.resnets.1.conv2: 1024.0
model.down_blocks.2.resnets.1.time_emb_proj: 4.0
model.down_blocks.3.resnets.0.conv1: 256.0
model.down_blocks.3.resnets.0.conv2: 256.0
model.down_blocks.3.resnets.0.time_emb_proj: 4.0
model.down_blocks.3.resnets.1.conv1: 256.0
model.down_blocks.3.resnets.1.conv2: 256.0
model.down_blocks.3.resnets.1.time_emb_proj: 4.0
model.mid_block.attentions.0.proj_in: 256.0
model.mid_block.attentions.0.proj_out: 256.0
model.mid_block.attentions.0.transformer_blocks.0.attn1.to_k: 256.0
model.mid_block.attentions.0.transformer_blocks.0.attn1.to_out.0: 256.0
model.mid_block.attentions.0.transformer_blocks.0.attn1.to_q: 256.0
model.mid_block.attentions.0.transformer_blocks.0.attn1.to_v: 256.0
model.mid_block.attentions.0.transformer_blocks.0.attn2.to_k: 184.8
model.mid_block.attentions.0.transformer_blocks.0.attn2.to_out.0: 256.0
model.mid_block.attentions.0.transformer_blocks.0.attn2.to_q: 256.0
model.mid_block.attentions.0.transformer_blocks.0.attn2.to_v: 184.8
model.mid_block.attentions.0.transformer_blocks.0.ff.net.0.proj: 256.0
model.mid_block.attentions.0.transformer_blocks.0.ff.net.2: 1024.0
model.mid_block.resnets.0.conv1: 256.0
model.mid_block.resnets.0.conv2: 256.0
model.mid_block.resnets.0.time_emb_proj: 4.0
model.mid_block.resnets.1.conv1: 256.0
model.mid_block.resnets.1.conv2: 256.0
model.mid_block.resnets.1.time_emb_proj: 4.0
model.time_embedding.linear_1: 1.0
model.time_embedding.linear_2: 4.0
model.up_blocks.0.resnets.0.conv1: 512.0
model.up_blocks.0.resnets.0.conv2: 256.0
model.up_blocks.0.resnets.0.conv_shortcut: 512.0
model.up_blocks.0.resnets.0.time_emb_proj: 4.0
model.up_blocks.0.resnets.1.conv1: 512.0
model.up_blocks.0.resnets.1.conv2: 256.0
model.up_blocks.0.resnets.1.conv_shortcut: 512.0
model.up_blocks.0.resnets.1.time_emb_proj: 4.0
model.up_blocks.0.resnets.2.conv1: 512.0
model.up_blocks.0.resnets.2.conv2: 256.0
model.up_blocks.0.resnets.2.conv_shortcut: 512.0
model.up_blocks.0.resnets.2.time_emb_proj: 4.0
model.up_blocks.0.upsamplers.0.conv: 1024.0
model.up_blocks.1.attentions.0.proj_in: 1024.0
model.up_blocks.1.attentions.0.proj_out: 1024.0
model.up_blocks.1.attentions.0.transformer_blocks.0.attn1.to_k: 1024.0
model.up_blocks.1.attentions.0.transformer_blocks.0.attn1.to_out.0: 1024.0
model.up_blocks.1.attentions.0.transformer_blocks.0.attn1.to_q: 1024.0
model.up_blocks.1.attentions.0.transformer_blocks.0.attn1.to_v: 1024.0
model.up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_k: 184.8
model.up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_out.0: 1024.0
model.up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_q: 1024.0
model.up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_v: 184.8
model.up_blocks.1.attentions.0.transformer_blocks.0.ff.net.0.proj: 1024.0
model.up_blocks.1.attentions.0.transformer_blocks.0.ff.net.2: 4096.0
model.up_blocks.1.attentions.1.proj_in: 1024.0
model.up_blocks.1.attentions.1.proj_out: 1024.0
model.up_blocks.1.attentions.1.transformer_blocks.0.attn1.to_k: 1024.0
model.up_blocks.1.attentions.1.transformer_blocks.0.attn1.to_out.0: 1024.0
model.up_blocks.1.attentions.1.transformer_blocks.0.attn1.to_q: 1024.0
model.up_blocks.1.attentions.1.transformer_blocks.0.attn1.to_v: 1024.0
model.up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_k: 184.8
model.up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_out.0: 1024.0
model.up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_q: 1024.0
model.up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_v: 184.8
model.up_blocks.1.attentions.1.transformer_blocks.0.ff.net.0.proj: 1024.0
model.up_blocks.1.attentions.1.transformer_blocks.0.ff.net.2: 4096.0
model.up_blocks.1.attentions.2.proj_in: 1024.0
model.up_blocks.1.attentions.2.proj_out: 1024.0
model.up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_k: 1024.0
model.up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_out.0: 1024.0
model.up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_q: 1024.0
model.up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_v: 1024.0
model.up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_k: 184.8
model.up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_out.0: 1024.0
model.up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_q: 1024.0
model.up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_v: 184.8
model.up_blocks.1.attentions.2.transformer_blocks.0.ff.net.0.proj: 1024.0
model.up_blocks.1.attentions.2.transformer_blocks.0.ff.net.2: 4096.0
model.up_blocks.1.resnets.0.conv1: 2048.0
model.up_blocks.1.resnets.0.conv2: 1024.0
model.up_blocks.1.resnets.0.conv_shortcut: 2048.0
model.up_blocks.1.resnets.0.time_emb_proj: 4.0
model.up_blocks.1.resnets.1.conv1: 2048.0
model.up_blocks.1.resnets.1.conv2: 1024.0
model.up_blocks.1.resnets.1.conv_shortcut: 2048.0
model.up_blocks.1.resnets.1.time_emb_proj: 4.0
model.up_blocks.1.resnets.2.conv1: 1536.0
model.up_blocks.1.resnets.2.conv2: 1024.0
model.up_blocks.1.resnets.2.conv_shortcut: 1536.0
model.up_blocks.1.resnets.2.time_emb_proj: 4.0
model.up_blocks.1.upsamplers.0.conv: 4096.0
model.up_blocks.2.attentions.0.proj_in: 2048.0
model.up_blocks.2.attentions.0.proj_out: 2048.0
model.up_blocks.2.attentions.0.transformer_blocks.0.attn1.to_k: 2048.0
model.up_blocks.2.attentions.0.transformer_blocks.0.attn1.to_out.0: 2048.0
model.up_blocks.2.attentions.0.transformer_blocks.0.attn1.to_q: 2048.0
model.up_blocks.2.attentions.0.transformer_blocks.0.attn1.to_v: 2048.0
model.up_blocks.2.attentions.0.transformer_blocks.0.attn2.to_k: 184.8
model.up_blocks.2.attentions.0.transformer_blocks.0.attn2.to_out.0: 2048.0
model.up_blocks.2.attentions.0.transformer_blocks.0.attn2.to_q: 2048.0
model.up_blocks.2.attentions.0.transformer_blocks.0.attn2.to_v: 184.8
model.up_blocks.2.attentions.0.transformer_blocks.0.ff.net.0.proj: 2048.0
model.up_blocks.2.attentions.0.transformer_blocks.0.ff.net.2: 8192.0
model.up_blocks.2.attentions.1.proj_in: 2048.0
model.up_blocks.2.attentions.1.proj_out: 2048.0
model.up_blocks.2.attentions.1.transformer_blocks.0.attn1.to_k: 2048.0
model.up_blocks.2.attentions.1.transformer_blocks.0.attn1.to_out.0: 2048.0
model.up_blocks.2.attentions.1.transformer_blocks.0.attn1.to_q: 2048.0
model.up_blocks.2.attentions.1.transformer_blocks.0.attn1.to_v: 2048.0
model.up_blocks.2.attentions.1.transformer_blocks.0.attn2.to_k: 184.8
model.up_blocks.2.attentions.1.transformer_blocks.0.attn2.to_out.0: 2048.0
model.up_blocks.2.attentions.1.transformer_blocks.0.attn2.to_q: 2048.0
model.up_blocks.2.attentions.1.transformer_blocks.0.attn2.to_v: 184.8
model.up_blocks.2.attentions.1.transformer_blocks.0.ff.net.0.proj: 2048.0
model.up_blocks.2.attentions.1.transformer_blocks.0.ff.net.2: 8192.0
model.up_blocks.2.attentions.2.proj_in: 2048.0
model.up_blocks.2.attentions.2.proj_out: 2048.0
model.up_blocks.2.attentions.2.transformer_blocks.0.attn1.to_k: 2048.0
model.up_blocks.2.attentions.2.transformer_blocks.0.attn1.to_out.0: 2048.0
model.up_blocks.2.attentions.2.transformer_blocks.0.attn1.to_q: 2048.0
model.up_blocks.2.attentions.2.transformer_blocks.0.attn1.to_v: 2048.0
model.up_blocks.2.attentions.2.transformer_blocks.0.attn2.to_k: 184.8
model.up_blocks.2.attentions.2.transformer_blocks.0.attn2.to_out.0: 2048.0
model.up_blocks.2.attentions.2.transformer_blocks.0.attn2.to_q: 2048.0
model.up_blocks.2.attentions.2.transformer_blocks.0.attn2.to_v: 184.8
model.up_blocks.2.attentions.2.transformer_blocks.0.ff.net.0.proj: 2048.0
model.up_blocks.2.attentions.2.transformer_blocks.0.ff.net.2: 8192.0
model.up_blocks.2.resnets.0.conv1: 6144.0
model.up_blocks.2.resnets.0.conv2: 2048.0
model.up_blocks.2.resnets.0.conv_shortcut: 6144.0
model.up_blocks.2.resnets.0.time_emb_proj: 4.0
model.up_blocks.2.resnets.1.conv1: 4096.0
model.up_blocks.2.resnets.1.conv2: 2048.0
model.up_blocks.2.resnets.1.conv_shortcut: 4096.0
model.up_blocks.2.resnets.1.time_emb_proj: 4.0
model.up_blocks.2.resnets.2.conv1: 3072.0
model.up_blocks.2.resnets.2.conv2: 2048.0
model.up_blocks.2.resnets.2.conv_shortcut: 3072.0
model.up_blocks.2.resnets.2.time_emb_proj: 4.0
model.up_blocks.2.upsamplers.0.conv: 8192.0
model.up_blocks.3.attentions.0.proj_in: 4096.0
model.up_blocks.3.attentions.0.proj_out: 4096.0
model.up_blocks.3.attentions.0.transformer_blocks.0.attn1.to_k: 4096.0
model.up_blocks.3.attentions.0.transformer_blocks.0.attn1.to_out.0: 4096.0
model.up_blocks.3.attentions.0.transformer_blocks.0.attn1.to_q: 4096.0
model.up_blocks.3.attentions.0.transformer_blocks.0.attn1.to_v: 4096.0
model.up_blocks.3.attentions.0.transformer_blocks.0.attn2.to_k: 184.8
model.up_blocks.3.attentions.0.transformer_blocks.0.attn2.to_out.0: 4096.0
model.up_blocks.3.attentions.0.transformer_blocks.0.attn2.to_q: 4096.0
model.up_blocks.3.attentions.0.transformer_blocks.0.attn2.to_v: 184.8
model.up_blocks.3.attentions.0.transformer_blocks.0.ff.net.0.proj: 4096.0
model.up_blocks.3.attentions.0.transformer_blocks.0.ff.net.2: 16384.0
model.up_blocks.3.attentions.1.proj_in: 4096.0
model.up_blocks.3.attentions.1.proj_out: 4096.0
model.up_blocks.3.attentions.1.transformer_blocks.0.attn1.to_k: 4096.0
model.up_blocks.3.attentions.1.transformer_blocks.0.attn1.to_out.0: 4096.0
model.up_blocks.3.attentions.1.transformer_blocks.0.attn1.to_q: 4096.0
model.up_blocks.3.attentions.1.transformer_blocks.0.attn1.to_v: 4096.0
model.up_blocks.3.attentions.1.transformer_blocks.0.attn2.to_k: 184.8
model.up_blocks.3.attentions.1.transformer_blocks.0.attn2.to_out.0: 4096.0
model.up_blocks.3.attentions.1.transformer_blocks.0.attn2.to_q: 4096.0
model.up_blocks.3.attentions.1.transformer_blocks.0.attn2.to_v: 184.8
model.up_blocks.3.attentions.1.transformer_blocks.0.ff.net.0.proj: 4096.0
model.up_blocks.3.attentions.1.transformer_blocks.0.ff.net.2: 16384.0
model.up_blocks.3.attentions.2.proj_in: 4096.0
model.up_blocks.3.attentions.2.proj_out: 4096.0
model.up_blocks.3.attentions.2.transformer_blocks.0.attn1.to_k: 4096.0
model.up_blocks.3.attentions.2.transformer_blocks.0.attn1.to_out.0: 4096.0
model.up_blocks.3.attentions.2.transformer_blocks.0.attn1.to_q: 4096.0
model.up_blocks.3.attentions.2.transformer_blocks.0.attn1.to_v: 4096.0
model.up_blocks.3.attentions.2.transformer_blocks.0.attn2.to_k: 184.8
model.up_blocks.3.attentions.2.transformer_blocks.0.attn2.to_out.0: 4096.0
model.up_blocks.3.attentions.2.transformer_blocks.0.attn2.to_q: 4096.0
model.up_blocks.3.attentions.2.transformer_blocks.0.attn2.to_v: 184.8
model.up_blocks.3.attentions.2.transformer_blocks.0.ff.net.0.proj: 4096.0
model.up_blocks.3.attentions.2.transformer_blocks.0.ff.net.2: 16384.0
model.up_blocks.3.resnets.0.conv1: 12288.0
model.up_blocks.3.resnets.0.conv2: 4096.0
model.up_blocks.3.resnets.0.conv_shortcut: 12288.0
model.up_blocks.3.resnets.0.time_emb_proj: 4.0
model.up_blocks.3.resnets.1.conv1: 8192.0
model.up_blocks.3.resnets.1.conv2: 4096.0
model.up_blocks.3.resnets.1.conv_shortcut: 8192.0
model.up_blocks.3.resnets.1.time_emb_proj: 4.0
model.up_blocks.3.resnets.2.conv1: 8192.0
model.up_blocks.3.resnets.2.conv2: 4096.0
model.up_blocks.3.resnets.2.conv_shortcut: 8192.0
model.up_blocks.3.resnets.2.time_emb_proj: 4.0
