model.conv_in: 1.0
model.conv_out: 1.0
model.down_blocks.0.attentions.0.proj_in: 8.88888888888889
model.down_blocks.0.attentions.0.proj_out: 8.88888888888889
model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_k: 8.88888888888889
model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_out.0: 8.88888888888889
model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_q: 8.88888888888889
model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_v: 8.88888888888889
model.down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_k: 21.333333333333332
model.down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_out.0: 8.88888888888889
model.down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_q: 8.88888888888889
model.down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_v: 21.333333333333332
model.down_blocks.0.attentions.0.transformer_blocks.0.ff.net.0.proj: 71.11111111111111
model.down_blocks.0.attentions.0.transformer_blocks.0.ff.net.2: 35.55555555555556
model.down_blocks.0.attentions.1.proj_in: 8.88888888888889
model.down_blocks.0.attentions.1.proj_out: 8.88888888888889
model.down_blocks.0.attentions.1.transformer_blocks.0.attn1.to_k: 8.88888888888889
model.down_blocks.0.attentions.1.transformer_blocks.0.attn1.to_out.0: 8.88888888888889
model.down_blocks.0.attentions.1.transformer_blocks.0.attn1.to_q: 8.88888888888889
model.down_blocks.0.attentions.1.transformer_blocks.0.attn1.to_v: 8.88888888888889
model.down_blocks.0.attentions.1.transformer_blocks.0.attn2.to_k: 21.333333333333332
model.down_blocks.0.attentions.1.transformer_blocks.0.attn2.to_out.0: 8.88888888888889
model.down_blocks.0.attentions.1.transformer_blocks.0.attn2.to_q: 8.88888888888889
model.down_blocks.0.attentions.1.transformer_blocks.0.attn2.to_v: 21.333333333333332
model.down_blocks.0.attentions.1.transformer_blocks.0.ff.net.0.proj: 71.11111111111111
model.down_blocks.0.attentions.1.transformer_blocks.0.ff.net.2: 35.55555555555556
model.down_blocks.0.downsamplers.0.conv: 80.0
model.down_blocks.0.resnets.0.conv1: 80.0
model.down_blocks.0.resnets.0.conv2: 80.0
model.down_blocks.0.resnets.0.time_emb_proj: 35.55555555555556
model.down_blocks.0.resnets.1.conv1: 80.0
model.down_blocks.0.resnets.1.conv2: 80.0
model.down_blocks.0.resnets.1.time_emb_proj: 35.55555555555556
model.down_blocks.1.attentions.0.proj_in: 35.55555555555556
model.down_blocks.1.attentions.0.proj_out: 35.55555555555556
model.down_blocks.1.attentions.0.transformer_blocks.0.attn1.to_k: 35.55555555555556
model.down_blocks.1.attentions.0.transformer_blocks.0.attn1.to_out.0: 35.55555555555556
model.down_blocks.1.attentions.0.transformer_blocks.0.attn1.to_q: 35.55555555555556
model.down_blocks.1.attentions.0.transformer_blocks.0.attn1.to_v: 35.55555555555556
model.down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_k: 42.666666666666664
model.down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_out.0: 35.55555555555556
model.down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_q: 35.55555555555556
model.down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_v: 42.666666666666664
model.down_blocks.1.attentions.0.transformer_blocks.0.ff.net.0.proj: 284.44444444444446
model.down_blocks.1.attentions.0.transformer_blocks.0.ff.net.2: 142.22222222222223
model.down_blocks.1.attentions.1.proj_in: 35.55555555555556
model.down_blocks.1.attentions.1.proj_out: 35.55555555555556
model.down_blocks.1.attentions.1.transformer_blocks.0.attn1.to_k: 35.55555555555556
model.down_blocks.1.attentions.1.transformer_blocks.0.attn1.to_out.0: 35.55555555555556
model.down_blocks.1.attentions.1.transformer_blocks.0.attn1.to_q: 35.55555555555556
model.down_blocks.1.attentions.1.transformer_blocks.0.attn1.to_v: 35.55555555555556
model.down_blocks.1.attentions.1.transformer_blocks.0.attn2.to_k: 42.666666666666664
model.down_blocks.1.attentions.1.transformer_blocks.0.attn2.to_out.0: 35.55555555555556
model.down_blocks.1.attentions.1.transformer_blocks.0.attn2.to_q: 35.55555555555556
model.down_blocks.1.attentions.1.transformer_blocks.0.attn2.to_v: 42.666666666666664
model.down_blocks.1.attentions.1.transformer_blocks.0.ff.net.0.proj: 284.44444444444446
model.down_blocks.1.attentions.1.transformer_blocks.0.ff.net.2: 142.22222222222223
model.down_blocks.1.downsamplers.0.conv: 320.0
model.down_blocks.1.resnets.0.conv1: 160.0
model.down_blocks.1.resnets.0.conv2: 320.0
model.down_blocks.1.resnets.0.conv_shortcut: 17.77777777777778
model.down_blocks.1.resnets.0.time_emb_proj: 71.11111111111111
model.down_blocks.1.resnets.1.conv1: 320.0
model.down_blocks.1.resnets.1.conv2: 320.0
model.down_blocks.1.resnets.1.time_emb_proj: 71.11111111111111
model.down_blocks.2.attentions.0.proj_in: 142.22222222222223
model.down_blocks.2.attentions.0.proj_out: 142.22222222222223
model.down_blocks.2.attentions.0.transformer_blocks.0.attn1.to_k: 142.22222222222223
model.down_blocks.2.attentions.0.transformer_blocks.0.attn1.to_out.0: 142.22222222222223
model.down_blocks.2.attentions.0.transformer_blocks.0.attn1.to_q: 142.22222222222223
model.down_blocks.2.attentions.0.transformer_blocks.0.attn1.to_v: 142.22222222222223
model.down_blocks.2.attentions.0.transformer_blocks.0.attn2.to_k: 85.33333333333333
model.down_blocks.2.attentions.0.transformer_blocks.0.attn2.to_out.0: 142.22222222222223
model.down_blocks.2.attentions.0.transformer_blocks.0.attn2.to_q: 142.22222222222223
model.down_blocks.2.attentions.0.transformer_blocks.0.attn2.to_v: 85.33333333333333
model.down_blocks.2.attentions.0.transformer_blocks.0.ff.net.0.proj: 1137.7777777777778
model.down_blocks.2.attentions.0.transformer_blocks.0.ff.net.2: 568.8888888888889
model.down_blocks.2.attentions.1.proj_in: 142.22222222222223
model.down_blocks.2.attentions.1.proj_out: 142.22222222222223
model.down_blocks.2.attentions.1.transformer_blocks.0.attn1.to_k: 142.22222222222223
model.down_blocks.2.attentions.1.transformer_blocks.0.attn1.to_out.0: 142.22222222222223
model.down_blocks.2.attentions.1.transformer_blocks.0.attn1.to_q: 142.22222222222223
model.down_blocks.2.attentions.1.transformer_blocks.0.attn1.to_v: 142.22222222222223
model.down_blocks.2.attentions.1.transformer_blocks.0.attn2.to_k: 85.33333333333333
model.down_blocks.2.attentions.1.transformer_blocks.0.attn2.to_out.0: 142.22222222222223
model.down_blocks.2.attentions.1.transformer_blocks.0.attn2.to_q: 142.22222222222223
model.down_blocks.2.attentions.1.transformer_blocks.0.attn2.to_v: 85.33333333333333
model.down_blocks.2.attentions.1.transformer_blocks.0.ff.net.0.proj: 1137.7777777777778
model.down_blocks.2.attentions.1.transformer_blocks.0.ff.net.2: 568.8888888888889
model.down_blocks.2.downsamplers.0.conv: 1280.0
model.down_blocks.2.resnets.0.conv1: 640.0
model.down_blocks.2.resnets.0.conv2: 1280.0
model.down_blocks.2.resnets.0.conv_shortcut: 71.11111111111111
model.down_blocks.2.resnets.0.time_emb_proj: 142.22222222222223
model.down_blocks.2.resnets.1.conv1: 1280.0
model.down_blocks.2.resnets.1.conv2: 1280.0
model.down_blocks.2.resnets.1.time_emb_proj: 142.22222222222223
model.down_blocks.3.resnets.0.conv1: 1280.0
model.down_blocks.3.resnets.0.conv2: 1280.0
model.down_blocks.3.resnets.0.time_emb_proj: 142.22222222222223
model.down_blocks.3.resnets.1.conv1: 1280.0
model.down_blocks.3.resnets.1.conv2: 1280.0
model.down_blocks.3.resnets.1.time_emb_proj: 142.22222222222223
model.mid_block.attentions.0.proj_in: 142.22222222222223
model.mid_block.attentions.0.proj_out: 142.22222222222223
model.mid_block.attentions.0.transformer_blocks.0.attn1.to_k: 142.22222222222223
model.mid_block.attentions.0.transformer_blocks.0.attn1.to_out.0: 142.22222222222223
model.mid_block.attentions.0.transformer_blocks.0.attn1.to_q: 142.22222222222223
model.mid_block.attentions.0.transformer_blocks.0.attn1.to_v: 142.22222222222223
model.mid_block.attentions.0.transformer_blocks.0.attn2.to_k: 85.33333333333333
model.mid_block.attentions.0.transformer_blocks.0.attn2.to_out.0: 142.22222222222223
model.mid_block.attentions.0.transformer_blocks.0.attn2.to_q: 142.22222222222223
model.mid_block.attentions.0.transformer_blocks.0.attn2.to_v: 85.33333333333333
model.mid_block.attentions.0.transformer_blocks.0.ff.net.0.proj: 1137.7777777777778
model.mid_block.attentions.0.transformer_blocks.0.ff.net.2: 568.8888888888889
model.mid_block.resnets.0.conv1: 1280.0
model.mid_block.resnets.0.conv2: 1280.0
model.mid_block.resnets.0.time_emb_proj: 142.22222222222223
model.mid_block.resnets.1.conv1: 1280.0
model.mid_block.resnets.1.conv2: 1280.0
model.mid_block.resnets.1.time_emb_proj: 142.22222222222223
model.time_embedding.linear_1: 35.55555555555556
model.time_embedding.linear_2: 142.22222222222223
model.up_blocks.0.resnets.0.conv1: 2560.0
model.up_blocks.0.resnets.0.conv2: 1280.0
model.up_blocks.0.resnets.0.conv_shortcut: 284.44444444444446
model.up_blocks.0.resnets.0.time_emb_proj: 142.22222222222223
model.up_blocks.0.resnets.1.conv1: 2560.0
model.up_blocks.0.resnets.1.conv2: 1280.0
model.up_blocks.0.resnets.1.conv_shortcut: 284.44444444444446
model.up_blocks.0.resnets.1.time_emb_proj: 142.22222222222223
model.up_blocks.0.resnets.2.conv1: 2560.0
model.up_blocks.0.resnets.2.conv2: 1280.0
model.up_blocks.0.resnets.2.conv_shortcut: 284.44444444444446
model.up_blocks.0.resnets.2.time_emb_proj: 142.22222222222223
model.up_blocks.0.upsamplers.0.conv: 1280.0
model.up_blocks.1.attentions.0.proj_in: 142.22222222222223
model.up_blocks.1.attentions.0.proj_out: 142.22222222222223
model.up_blocks.1.attentions.0.transformer_blocks.0.attn1.to_k: 142.22222222222223
model.up_blocks.1.attentions.0.transformer_blocks.0.attn1.to_out.0: 142.22222222222223
model.up_blocks.1.attentions.0.transformer_blocks.0.attn1.to_q: 142.22222222222223
model.up_blocks.1.attentions.0.transformer_blocks.0.attn1.to_v: 142.22222222222223
model.up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_k: 85.33333333333333
model.up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_out.0: 142.22222222222223
model.up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_q: 142.22222222222223
model.up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_v: 85.33333333333333
model.up_blocks.1.attentions.0.transformer_blocks.0.ff.net.0.proj: 1137.7777777777778
model.up_blocks.1.attentions.0.transformer_blocks.0.ff.net.2: 568.8888888888889
model.up_blocks.1.attentions.1.proj_in: 142.22222222222223
model.up_blocks.1.attentions.1.proj_out: 142.22222222222223
model.up_blocks.1.attentions.1.transformer_blocks.0.attn1.to_k: 142.22222222222223
model.up_blocks.1.attentions.1.transformer_blocks.0.attn1.to_out.0: 142.22222222222223
model.up_blocks.1.attentions.1.transformer_blocks.0.attn1.to_q: 142.22222222222223
model.up_blocks.1.attentions.1.transformer_blocks.0.attn1.to_v: 142.22222222222223
model.up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_k: 85.33333333333333
model.up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_out.0: 142.22222222222223
model.up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_q: 142.22222222222223
model.up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_v: 85.33333333333333
model.up_blocks.1.attentions.1.transformer_blocks.0.ff.net.0.proj: 1137.7777777777778
model.up_blocks.1.attentions.1.transformer_blocks.0.ff.net.2: 568.8888888888889
model.up_blocks.1.attentions.2.proj_in: 142.22222222222223
model.up_blocks.1.attentions.2.proj_out: 142.22222222222223
model.up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_k: 142.22222222222223
model.up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_out.0: 142.22222222222223
model.up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_q: 142.22222222222223
model.up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_v: 142.22222222222223
model.up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_k: 85.33333333333333
model.up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_out.0: 142.22222222222223
model.up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_q: 142.22222222222223
model.up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_v: 85.33333333333333
model.up_blocks.1.attentions.2.transformer_blocks.0.ff.net.0.proj: 1137.7777777777778
model.up_blocks.1.attentions.2.transformer_blocks.0.ff.net.2: 568.8888888888889
model.up_blocks.1.resnets.0.conv1: 2560.0
model.up_blocks.1.resnets.0.conv2: 1280.0
model.up_blocks.1.resnets.0.conv_shortcut: 284.44444444444446
model.up_blocks.1.resnets.0.time_emb_proj: 142.22222222222223
model.up_blocks.1.resnets.1.conv1: 2560.0
model.up_blocks.1.resnets.1.conv2: 1280.0
model.up_blocks.1.resnets.1.conv_shortcut: 284.44444444444446
model.up_blocks.1.resnets.1.time_emb_proj: 142.22222222222223
model.up_blocks.1.resnets.2.conv1: 1920.0
model.up_blocks.1.resnets.2.conv2: 1280.0
model.up_blocks.1.resnets.2.conv_shortcut: 213.33333333333334
model.up_blocks.1.resnets.2.time_emb_proj: 142.22222222222223
model.up_blocks.1.upsamplers.0.conv: 1280.0
model.up_blocks.2.attentions.0.proj_in: 35.55555555555556
model.up_blocks.2.attentions.0.proj_out: 35.55555555555556
model.up_blocks.2.attentions.0.transformer_blocks.0.attn1.to_k: 35.55555555555556
model.up_blocks.2.attentions.0.transformer_blocks.0.attn1.to_out.0: 35.55555555555556
model.up_blocks.2.attentions.0.transformer_blocks.0.attn1.to_q: 35.55555555555556
model.up_blocks.2.attentions.0.transformer_blocks.0.attn1.to_v: 35.55555555555556
model.up_blocks.2.attentions.0.transformer_blocks.0.attn2.to_k: 42.666666666666664
model.up_blocks.2.attentions.0.transformer_blocks.0.attn2.to_out.0: 35.55555555555556
model.up_blocks.2.attentions.0.transformer_blocks.0.attn2.to_q: 35.55555555555556
model.up_blocks.2.attentions.0.transformer_blocks.0.attn2.to_v: 42.666666666666664
model.up_blocks.2.attentions.0.transformer_blocks.0.ff.net.0.proj: 284.44444444444446
model.up_blocks.2.attentions.0.transformer_blocks.0.ff.net.2: 142.22222222222223
model.up_blocks.2.attentions.1.proj_in: 35.55555555555556
model.up_blocks.2.attentions.1.proj_out: 35.55555555555556
model.up_blocks.2.attentions.1.transformer_blocks.0.attn1.to_k: 35.55555555555556
model.up_blocks.2.attentions.1.transformer_blocks.0.attn1.to_out.0: 35.55555555555556
model.up_blocks.2.attentions.1.transformer_blocks.0.attn1.to_q: 35.55555555555556
model.up_blocks.2.attentions.1.transformer_blocks.0.attn1.to_v: 35.55555555555556
model.up_blocks.2.attentions.1.transformer_blocks.0.attn2.to_k: 42.666666666666664
model.up_blocks.2.attentions.1.transformer_blocks.0.attn2.to_out.0: 35.55555555555556
model.up_blocks.2.attentions.1.transformer_blocks.0.attn2.to_q: 35.55555555555556
model.up_blocks.2.attentions.1.transformer_blocks.0.attn2.to_v: 42.666666666666664
model.up_blocks.2.attentions.1.transformer_blocks.0.ff.net.0.proj: 284.44444444444446
model.up_blocks.2.attentions.1.transformer_blocks.0.ff.net.2: 142.22222222222223
model.up_blocks.2.attentions.2.proj_in: 35.55555555555556
model.up_blocks.2.attentions.2.proj_out: 35.55555555555556
model.up_blocks.2.attentions.2.transformer_blocks.0.attn1.to_k: 35.55555555555556
model.up_blocks.2.attentions.2.transformer_blocks.0.attn1.to_out.0: 35.55555555555556
model.up_blocks.2.attentions.2.transformer_blocks.0.attn1.to_q: 35.55555555555556
model.up_blocks.2.attentions.2.transformer_blocks.0.attn1.to_v: 35.55555555555556
model.up_blocks.2.attentions.2.transformer_blocks.0.attn2.to_k: 42.666666666666664
model.up_blocks.2.attentions.2.transformer_blocks.0.attn2.to_out.0: 35.55555555555556
model.up_blocks.2.attentions.2.transformer_blocks.0.attn2.to_q: 35.55555555555556
model.up_blocks.2.attentions.2.transformer_blocks.0.attn2.to_v: 42.666666666666664
model.up_blocks.2.attentions.2.transformer_blocks.0.ff.net.0.proj: 284.44444444444446
model.up_blocks.2.attentions.2.transformer_blocks.0.ff.net.2: 142.22222222222223
model.up_blocks.2.resnets.0.conv1: 960.0
model.up_blocks.2.resnets.0.conv2: 320.0
model.up_blocks.2.resnets.0.conv_shortcut: 106.66666666666667
model.up_blocks.2.resnets.0.time_emb_proj: 71.11111111111111
model.up_blocks.2.resnets.1.conv1: 640.0
model.up_blocks.2.resnets.1.conv2: 320.0
model.up_blocks.2.resnets.1.conv_shortcut: 71.11111111111111
model.up_blocks.2.resnets.1.time_emb_proj: 71.11111111111111
model.up_blocks.2.resnets.2.conv1: 480.0
model.up_blocks.2.resnets.2.conv2: 320.0
model.up_blocks.2.resnets.2.conv_shortcut: 53.333333333333336
model.up_blocks.2.resnets.2.time_emb_proj: 71.11111111111111
model.up_blocks.2.upsamplers.0.conv: 320.0
model.up_blocks.3.attentions.0.proj_in: 8.88888888888889
model.up_blocks.3.attentions.0.proj_out: 8.88888888888889
model.up_blocks.3.attentions.0.transformer_blocks.0.attn1.to_k: 8.88888888888889
model.up_blocks.3.attentions.0.transformer_blocks.0.attn1.to_out.0: 8.88888888888889
model.up_blocks.3.attentions.0.transformer_blocks.0.attn1.to_q: 8.88888888888889
model.up_blocks.3.attentions.0.transformer_blocks.0.attn1.to_v: 8.88888888888889
model.up_blocks.3.attentions.0.transformer_blocks.0.attn2.to_k: 21.333333333333332
model.up_blocks.3.attentions.0.transformer_blocks.0.attn2.to_out.0: 8.88888888888889
model.up_blocks.3.attentions.0.transformer_blocks.0.attn2.to_q: 8.88888888888889
model.up_blocks.3.attentions.0.transformer_blocks.0.attn2.to_v: 21.333333333333332
model.up_blocks.3.attentions.0.transformer_blocks.0.ff.net.0.proj: 71.11111111111111
model.up_blocks.3.attentions.0.transformer_blocks.0.ff.net.2: 35.55555555555556
model.up_blocks.3.attentions.1.proj_in: 8.88888888888889
model.up_blocks.3.attentions.1.proj_out: 8.88888888888889
model.up_blocks.3.attentions.1.transformer_blocks.0.attn1.to_k: 8.88888888888889
model.up_blocks.3.attentions.1.transformer_blocks.0.attn1.to_out.0: 8.88888888888889
model.up_blocks.3.attentions.1.transformer_blocks.0.attn1.to_q: 8.88888888888889
model.up_blocks.3.attentions.1.transformer_blocks.0.attn1.to_v: 8.88888888888889
model.up_blocks.3.attentions.1.transformer_blocks.0.attn2.to_k: 21.333333333333332
model.up_blocks.3.attentions.1.transformer_blocks.0.attn2.to_out.0: 8.88888888888889
model.up_blocks.3.attentions.1.transformer_blocks.0.attn2.to_q: 8.88888888888889
model.up_blocks.3.attentions.1.transformer_blocks.0.attn2.to_v: 21.333333333333332
model.up_blocks.3.attentions.1.transformer_blocks.0.ff.net.0.proj: 71.11111111111111
model.up_blocks.3.attentions.1.transformer_blocks.0.ff.net.2: 35.55555555555556
model.up_blocks.3.attentions.2.proj_in: 8.88888888888889
model.up_blocks.3.attentions.2.proj_out: 8.88888888888889
model.up_blocks.3.attentions.2.transformer_blocks.0.attn1.to_k: 8.88888888888889
model.up_blocks.3.attentions.2.transformer_blocks.0.attn1.to_out.0: 8.88888888888889
model.up_blocks.3.attentions.2.transformer_blocks.0.attn1.to_q: 8.88888888888889
model.up_blocks.3.attentions.2.transformer_blocks.0.attn1.to_v: 8.88888888888889
model.up_blocks.3.attentions.2.transformer_blocks.0.attn2.to_k: 21.333333333333332
model.up_blocks.3.attentions.2.transformer_blocks.0.attn2.to_out.0: 8.88888888888889
model.up_blocks.3.attentions.2.transformer_blocks.0.attn2.to_q: 8.88888888888889
model.up_blocks.3.attentions.2.transformer_blocks.0.attn2.to_v: 21.333333333333332
model.up_blocks.3.attentions.2.transformer_blocks.0.ff.net.0.proj: 71.11111111111111
model.up_blocks.3.attentions.2.transformer_blocks.0.ff.net.2: 35.55555555555556
model.up_blocks.3.resnets.0.conv1: 240.0
model.up_blocks.3.resnets.0.conv2: 80.0
model.up_blocks.3.resnets.0.conv_shortcut: 26.666666666666668
model.up_blocks.3.resnets.0.time_emb_proj: 35.55555555555556
model.up_blocks.3.resnets.1.conv1: 160.0
model.up_blocks.3.resnets.1.conv2: 80.0
model.up_blocks.3.resnets.1.conv_shortcut: 17.77777777777778
model.up_blocks.3.resnets.1.time_emb_proj: 35.55555555555556
model.up_blocks.3.resnets.2.conv1: 160.0
model.up_blocks.3.resnets.2.conv2: 80.0
model.up_blocks.3.resnets.2.conv_shortcut: 17.77777777777778
model.up_blocks.3.resnets.2.time_emb_proj: 35.55555555555556
